/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 04-mar-2010, 17:19:51
 */

package icaro.aplicaciones.recursos.visualizacionPrediccion.imp.gui;

import icaro.aplicaciones.recursos.visualizacionPrediccion.imp.ClaseGeneradoraVisualizacionPrediccion;
import icaro.aplicaciones.recursos.visualizacionPrediccion.imp.NotificacionesEventosVisPrediccion;
import icaro.aplicaciones.recursos.visualizacionPrediccion.imp.swing.VentanaEstandar;

/**
 *
 * @author PAblo 
 */
public class PanelPrediccionUsuario extends VentanaEstandar {
    private static final long serialVersionUID = 1L;

			/**
			 * @uml.property  name="usoAgente"
			 * @uml.associationEnd  multiplicity="(1 1)"
			 */
    private NotificacionesEventosVisPrediccion usoAgente; //comunicacion con el agente (control)

    /** Creates new form NewJFrame */
    public PanelPrediccionUsuario() {
        initComponents();
    }

    public PanelPrediccionUsuario(ClaseGeneradoraVisualizacionPrediccion visualizador,NotificacionesEventosVisPrediccion notifEventos) {
//        usoAgente = new NotificacionesEventosRecurso(visualizador);
	usoAgente = notifEventos;
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonBorrar = new javax.swing.JButton();
        botonPredecir = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        textoEquipo1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textoFecha = new javax.swing.JTextField();
        textoEquipo2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Prediccion");

        botonBorrar.setText("Borrar campos");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonPredecir.setText("Predecir");
        botonPredecir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPredecirActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jLabel1.setText("Equipo local");

        jLabel2.setText("Equipo visitante");

        jLabel3.setText("Fecha");

        textoEquipo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoEquipo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textoEquipo1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(textoFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(textoEquipo2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonPredecir)
                        .addGap(47, 47, 47)
                        .addComponent(botonBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSalir)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoEquipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textoEquipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(textoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonPredecir)
                    .addComponent(botonBorrar)
                    .addComponent(botonSalir))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPredecirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPredecirActionPerformed
        String usr = textoEquipo1.getText();
        String pwd = textoEquipo2.getText();
        if((usr.equals(""))||(pwd.equals("")))
            usoAgente.getVisualizador().mostrarMensajeError("Prediccion no valida", "Verifique que ha introducido equipos y fecha correctas");
        else
            usoAgente.peticionPrediccion(textoEquipo1.getText(),textoEquipo2.getText(), textoFecha.getText());
    }//GEN-LAST:event_botonPredecirActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        textoEquipo1.setText("");
	textoEquipo2.setText("");
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
       usoAgente.notificacionCierreSistema();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void textoEquipo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoEquipo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoEquipo2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPrediccionUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonPredecir;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField textoEquipo1;
    private javax.swing.JTextField textoEquipo2;
    private javax.swing.JTextField textoFecha;
    // End of variables declaration//GEN-END:variables

}
